### ISSUE TITLE
Plugin fails to build on cordova ios@4.1.0

### ISSUE THREAD

**Issue by paweldziura** [christocracy/cordova-plugin-background-fetch#28]
Hi,

I updated the project to newest ios cordova (4.1.0).
When building the project i get an error:

> 
> /Users/Me/Projects/project/platforms/ios/ **App/Plugins/org.transistorsoft.cordova.plugin.background.fetch/CDVBackgroundFetch.m:8:9: fatal error: 'Cordova/CDVJSON.h' file not found**
> #import <Cordova/CDVJSON.h>
> 
> ** BUILD FAILED **
> 
> The following build commands failed:
>         CompileC build/App\ App.build/Debug-iphonesimulator/App\ App.build/Objects-normal/i386/CDVBackgroundFetch.o Project\ App/Plugins/org.transistorsoft.cordova.plugin.background.fetch/CDVBackgroundFetch.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> 
> ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Me/Projects/project/platforms/ios/cordova/build-debug.xcconfig,-project,Project App.xcodeproj,ARCHS=i386,-target,Project App,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Me/Projects/project/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Me/Projects/project/platforms/ios/build/sharedpch
> You may not have the required environment or OS to build this project
> 
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/Me/Projects/project/platforms/ios/cordova/build-debug.xcconfig,-project,Project App.xcodeproj,ARCHS=i386,-target,Project App,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/Me/Projects/project/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/Me/Projects/project/platforms/ios/build/sharedpch

Removing the plugin makes the build successful.
Thanks
Pawel

**Comment by christocracy** [comment]
`CDVJSON` is probably obsolete in latest Cordova.  The plugin hasn't been touched in a long time.  If you'd like to fix it, send me a pull-request.

**Comment by Jacse** [comment]
As far as I can tell the plugin doesn't actually use `CDVJSON` - is that correct @christocracy? In that case isn't it simply a question of removing said include?

Never once wrote any Objective-C so I honestly have no idea how it works - I just did a ctrl+f search

**Comment by paweldziura** [comment]
@Jacse, @christocracy I commented out the "#import <Cordova/CDVJSON.h>" in CDVBackgroundFetch.m and after that project was built correctly. I haven't tested if everything is working fine yet.

**Comment by braianj** [comment]
I have commented but now it return me a lot of bugs more, no body using google maps this days?

**Comment by christocracy** [comment]
What?

On Thursday, July 14, 2016, braianj <notifications@github.com> wrote:

> I have commented but now it return me a lot of bugs more, no body using
> google maps this days?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/28#issuecomment-232802667>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l88FscYbVmp9HjKzcgjriz-XNH63ks5qVq6_gaJpZM4Hq1FW>
> .
>


-- 
Snet form Gmail Mobile

**Comment by braianj** [comment]
Since you said that "The plugin hasn't been touched in a long time".
I just install plugin as last week and it can build the project 

```
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:24:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:28:45: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginScrollView.debugView.webView = self.webView;
                                            ^ ~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:34:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
    self.pluginLayer.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:167:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
        self.mapCtrl.webView = self.webView;
                             ^ ~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector 'initWithWebView:'
        Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
                                                          ^~~~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:186:38: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
            self.pluginLayer.webView = self.webView;
                                     ^ ~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector 'initWithWebView:'
                pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
                                                                   ^~~~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
    [self.webView stringByEvaluatingJavaScriptFromString:jsString];
     ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:404:34: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
        self.pluginLayer.webView = self.webView;
                                 ^ ~~~~~~~~~~~~
6 warnings and 3 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/proyect_app.build/Debug-iphonesimulator/proyect_app.build/Objects-normal/i386/GoogleMaps.o proyect_app/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/proyect_app/platforms/ios/cordova/build-debug.xcconfig,-project,proyect_app.xcodeproj,ARCHS=i386,-target,proyect_app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/proyect_app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/proyect_app/platforms/ios/build/sharedpch
```

**Comment by christocracy** [comment]
Are you sure you're commenting at the right place?  This is
cordova-plugin-background-fetch.

I see no errors referencing this plugin.

Maybe you need to go talk to plugin.google.maps/GoogleMaps

On Thursday, July 14, 2016, braianj <notifications@github.com> wrote:

> Since you said that "The plugin hasn't been touched in a long time".
> I just install plugin as last week and it can build the project
>
> /proyect_app/platforms/ios/proyect_app/Plugins/.m:24:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>     self.pluginLayer.webView = self.webView;
>                              ^ ~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:28:45: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>     self.pluginScrollView.debugView.webView = self.webView;
>                                             ^ ~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:34:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>     self.pluginLayer.webView = self.webView;
>                              ^ ~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:167:30: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>         self.mapCtrl.webView = self.webView;
>                              ^ ~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:176:59: error: no known instance method for selector 'initWithWebView:'
>         Map *mapClass = [[NSClassFromString(@"Map")alloc] initWithWebView:self.webView];
>                                                           ^~~~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:186:38: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>             self.pluginLayer.webView = self.webView;
>                                      ^ ~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:245:68: error: no known instance method for selector 'initWithWebView:'
>                 pluginClass = [[NSClassFromString(className)alloc] initWithWebView:self.webView];
>                                                                    ^~~~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:321:19: error: no visible @interface for 'UIView' declares the selector 'stringByEvaluatingJavaScriptFromString:'
>     [self.webView stringByEvaluatingJavaScriptFromString:jsString];
>      ~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /proyect_app/platforms/ios/proyect_app/Plugins/plugin.google.maps/GoogleMaps.m:404:34: warning: incompatible pointer types assigning to 'UIWebView *' from 'UIView *' [-Wincompatible-pointer-types]
>         self.pluginLayer.webView = self.webView;
>                                  ^ ~~~~~~~~~~~~
> 6 warnings and 3 errors generated.
>
> ** BUILD FAILED **
>
>
> The following build commands failed:
>     CompileC build/proyect_app.build/Debug-iphonesimulator/proyect_app.build/Objects-normal/i386/GoogleMaps.o proyect_app/Plugins/plugin.google.maps/GoogleMaps.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,/proyect_app/platforms/ios/cordova/build-debug.xcconfig,-project,proyect_app.xcodeproj,ARCHS=i386,-target,proyect_app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/proyect_app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/proyect_app/platforms/ios/build/sharedpch
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/28#issuecomment-232804037>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAA6l-iFLbtXwoV8NtOxc0QPNBjFhpzEks5qVrAggaJpZM4Hq1FW>
> .
>


-- 
Snet form Gmail Mobile

**Comment by braianj** [comment]
@christocracy sorry about that, that's why erase those comments. Sorry again
